blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/paulodiovani/ai-model-access-analysis/discussions
    about: Ask questions or start a discussion about AI model access.
